### ISSUE TITLE
ObjectToObject DynamicResource

### ISSUE THREAD

**Issue by Symbai** [DevExpress/DevExpress.Mvvm.Free#10]
Hi,

I've tried following the example on DevExpress.com except that I use a dynamicresource as brush instead of a fixed color but it fails. Any workaround?

`<dxmvvm:MapItem Source="True" Target="{DynamicResource TestBrushInResourceDictionary}" />`

**Comment by AlexanderEgorov** [comment]
Hi, 

Yes, this is a WPF restriction. You can create a behavior that searches for a necessary resource with the FrameworkElement.FindResource method.
If you have any problem implementing this solution, please contact our support team at: https://www.devexpress.com/Support/Center/Question/Create
