### ISSUE TITLE
how to fix this wrong

### ISSUE THREAD

**Issue by nocanstillbb** [DevExpress/DevExpress.Mvvm.Free#13]
Details about calling real-time (JIT) debugging instead of this dialog box,

See the end of this message.

************************** Abnormal Text****************************

System.ArgumentException:

Parameter name: args

In DevExpress. Mvvm. UI. Native. JumpAction ManagerClient. Run (String [] args, Action `1 startProcess) location C: Users Bing\ Desktop DevExpress. Mvvm. Free-master DevExpress. Mvm. UI. Application Jumper Launcher\ JumpionsManager. Clics: line number 271.

In DevExpress.Mvvm.UI.Application JumpTask Launcher.Program.Main (String[] args) location C: Users\ Bing Desktop\ DevExpress.Mvvvm.Free-master DevExpress.Mvvvm.UI.Application JumpTask Launcher\ Program.cs: line number 11

**************************** Loaded Assemblies********************

Mscorlib

Assembly version: 4.0.0.0

Win32 Version: 4.7.3221.0 Build by: NET472REL1LAST_C

Basic code: file://C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll

--------------------------------------------------------------------------------------------------------------------------------------------

DevExpress. Mvvm. UI. Application JumpTask Launcher

Assembly version: 18.2.0.0

Win32 Version: 18.2.0.0

Basic code: file://C:/Users/Bing/Desktop/DevExpress.Mvvm.Free-master/Bin/Framework 4/DevExpress.Mvvvm.UI.Application JumpTask Launcher.exe

--------------------------------------------------------------------------------------------------------------------------------------------

System

Assembly version: 4.0.0.0

Win32 Version: 4.7.3190.0 Build by: NET472REL1LAST_C

Basic code: file://C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0_u b77a5c561934e089/System.dll

--------------------------------------------------------------------------------------------------------------------------------------------

System.Windows.Forms

Assembly version: 4.0.0.0

Win32 Version: 4.7.3221.0 Build by: NET472REL1LAST_C

Basic code: file://C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0_u b77a5c561934e089/System.Windows.Forms.dll

--------------------------------------------------------------------------------------------------------------------------------------------

System.Drawing

Assembly version: 4.0.0.0

Win32 Version: 4.7.3056.0 Build by: NET472REL1

Basic code: file://C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0_u b03f5f7f11d50a3a/System.Drawing.dll

--------------------------------------------------------------------------------------------------------------------------------------------

System.Core

Assembly version: 4.0.0.0

Win32 Version: 4.7.3221.0 Build by: NET472REL1LAST_C

Basic code: file://C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0_u b77a5c561934e089/System.Core.dll

--------------------------------------------------------------------------------------------------------------------------------------------

System.Configuration

Assembly version: 4.0.0.0

Win32 Version: 4.7.3056.0 Build by: NET472REL1

Basic code: file://C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0_u b03f5f7f11d50a3a/System.Configuration.dll

--------------------------------------------------------------------------------------------------------------------------------------------

System.Xml

Assembly version: 4.0.0.0

Win32 Version: 4.7.3056.0 Build by: NET472REL1

Basic code: file://C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0_u b77a5c561934e089/System.Xml.dll

--------------------------------------------------------------------------------------------------------------------------------------------

Mscorlib.resources

Assembly version: 4.0.0.0

Win32 Version: 4.7.3056.0 Build by: NET472REL1

Basic code: file://C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_zh-Hans_b77a5c561934e089/mscorlib.resources.dll

--------------------------------------------------------------------------------------------------------------------------------------------

System. Windows. Forms. Resources

Assembly version: 4.0.0.0

Win32 Version: 4.7.3056.0 Build by: NET472REL1

Basic code: file://C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0.0_zh-Hans_b77a5c561934e089/System.Windows.Forms.dll.

--------------------------------------------------------------------------------------------------------------------------------------------

************************ JIT Debugging**************************************

To enable real-time (JIT) debugging,

The system. windows. forms section of the application or computer's. config file (machine. config) must be set

JitDebugging value.

The application must also be enabled when compiling

Debugging.

For example:

<configuration>

<system.windows.forms jitDebugging="true"/>

</configuration>

Any unhandled exception after JIT debugging is enabled

Will be sent to the JIT debugger registered on this computer.

Instead of being handled by this dialog box.

**Comment by AlexanderEgorov** [comment]
Hi,
 
Would you please provide more details about the issue? How can I reproduce it on my side? If it is possible, please provide a sample project.
 
Looking forward to your response.

**Comment by nocanstillbb** [comment]
thank you for your response.
when i just download -> build -> run with visual Stuidio this wrong messagebox is showed.
![image](https://user-images.githubusercontent.com/22405678/49706903-9a91ac00-fc63-11e8-8a29-2c44a6ad7838.png)

**Comment by nocanstillbb** [comment]
> Hi,
> 
> I have tried to reproduce the problem with [a sample from our documentation](https://documentation.devexpress.com/WPF/18163/MVVM-Framework/Services/Predefined-Set/ApplicationJumpListService), but without success.
> 
> I have attached the sample. Would you please modify it to demonstrate the issue?
> [DXSampleApplicationJumpListService.zip](https://github.com/DevExpress/DevExpress.Mvvm.Free/files/2662177/DXSampleApplicationJumpListService.zip)

i have not changed anything.  
but the  project that  i debuged not that project you attached project.

![image](https://user-images.githubusercontent.com/22405678/49841117-461c3700-fdf1-11e8-8e36-a567b98c8347.png)

i downloaded it from this place that  follow pic show 
![image](https://user-images.githubusercontent.com/22405678/49841311-128ddc80-fdf2-11e8-8ee6-b4a96be78cb0.png)

**Comment by AlexanderEgorov** [comment]
I accidentally missed a notification of your inquiry. Please accept my apologies for the inconvenience. If this exception is still thrown, please let me know.
