### ISSUE TITLE
Clone Project

### ISSUE THREAD

**Issue by nhphuc699** [DevExpress/DevExpress.Mvvm.Free#14]
Dear Sir/ Madam
   Can I rebuilded this project for my own app (My app using .net 4.5.1, I rebuiled this project to .net 4.5.1 and it run with no problem). Do you allow it? (License etc..).
  Please answer me.
  Thanhks You!

**Comment by AlexanderEgorov** [comment]
Hi,   
Yes, of course. Our free MVVM version is under the MIT license. So, you can modify our code without any limitation.
