### ISSUE TITLE
[Question] usage on MVVM.Free

### ISSUE THREAD

**Issue by wstaelens** [DevExpress/DevExpress.Mvvm.Free#18]
> Note that the free version of the framework is not compatible with the DevExpress WPF suite.

Does this mean that I can start development using DevExpress.Mvvm.Free and when I buy DX WPF I just have to remove nuget package or assembly from mvvm.free to the full one?

**Comment by AlexanderEgorov** [comment]
Yes, this should not be a problem if you did not modify the code in the free library.
