### ISSUE TITLE
[Q] WPF MVVM + .NET 5 Microsoft.Extensions.DependencyInjection 

### ISSUE THREAD

**Issue by wstaelens** [DevExpress/DevExpress.Mvvm.Free#19]
Just getting started, I'm used to working with Ninject and Caliburn Micro.

For a new project I'm starting with DX MVVM, WPF and Microsoft DI (Microsoft.Extensions.DependencyInjection) in .NET 5.

I'm just strugling to get started as the way of working seems to be a bit different and the documentation is not always giving me an answer.

In the code below you will see that I want to show TestView when I run the application:

```
<Application x:Class="Foo.Bar.Wpf.App"
             xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:local="clr-namespace:Foo.Bar.Wpf"
             Startup="OnStartup">
    <Application.Resources>
         
    </Application.Resources>
</Application>

  public partial class App : Application
  {
    private readonly ServiceProvider _ServiceProvider;

    public App()
    {
      var serviceCollection = new ServiceCollection();
      ConfigureServices(serviceCollection);
      _ServiceProvider = serviceCollection.BuildServiceProvider(); 
    }

    private void ConfigureServices(IServiceCollection services)
    {

      services.AddSingleton<IWindowService, WindowService>();

    }

    private void OnStartup(object sender, StartupEventArgs e)
    {
      // how to get the viewmodel to auto inject constructor parameters?
      var myViewModel = new ViewModels.Foo.TestViewModel(); 
      var ws = _ServiceProvider.GetService<IWindowService>();
      ws.Show("TestView", myViewModel);
    }

  }

  public class TestViewModel : ViewModelBase
  {
    public TestViewModel()
    {
    }
  }

<UserControl ...
             xmlns:dxmvvm="http://schemas.devexpress.com/winfx/2008/xaml/mvvm"
             xmlns:ViewModel="clr-namespace:Foo.Bar.Wpf.ViewModels.Foo"
             DataContext="{dxmvvm:ViewModelSource ViewModel:TestViewModel}">
</UserControl>
```

1. Is this the correct way of registering the DX Services to the MS IoC/DI? or should they be defined in App.xaml resources and requested via ServiceContainer.Default.GetService<...>() ? (can you do this like I did via the MS IoC/DI or how should it be done? cf. https://docs.devexpress.com/WPF/17444/mvvm-framework/services/getting-started )
2. In case my viewmodel has constructor parameters, how do I create/request a VM so that my services (own and DX) are automatically injected?
3. Should the DX services always be registered in the specific View xaml (or App.xaml) ?

**Comment by AlexanderEgorov** [comment]
Hello,

Thank you for the question.
MVVM services are different from traditional Dependency Injection (DI) services. They are designed as a bridge between View and ViewModel.
When you define our MVVM service in XAML, it is registered in the underlying DataContext (ViewModel), so this view model can operate with its View through the service interface. Some services can be registered at the Application.Resources level - this allows you to access these services from any view model.
Although you can register our predefined MVVM services in a DI container, I do not recommend this approach. It would be better to create your own services for your purposes instead. 
I created a sample to demonstrate how you can do this. Please review it. [WpfApp1.zip](https://github.com/DevExpress/DevExpress.Mvvm.Free/files/6156431/WpfApp1.zip)

**Comment by wstaelens** [comment]
Thank you @AlexanderEgorov helpful.  So basically if I summarize:

1. use MS DI container for injection of own logic.
2. register DX services either locally in view or in app.xaml to communicate between V and VM.
3. if I have a VM where I want to inject parameters with own logic, request the VM via the MS DI so that own logic gets injected there and register the DX services in the V / VM with the ViewModelBase.GetService.
4. once a VM/V has been creating creating and calling other VM/V's should happen via the DX services, only you might want to manually create a new ViewModel class or request it via the MS DI.

Correct?

Last thing I have seen is that you register both View and ViewModel in app.xaml.cs allowing you to call .Show() on the view.

Let's say this is a "view-first" way of working. Can it be done via ViewLocator so that you request the ViewModel via MS DI so that own logic gets injected in the constructor of the VM and that the View is attached automatically?

Maybe something like (doesn't work):

```
    <Application.Resources>
    <dxmvvm:WindowService x:Key="WindowService" />
  </Application.Resources>

    private void ConfigureServices(IServiceCollection services)
    {
        services.AddScoped<ViewModels.Foo.TestViewModel>();
    }

    private void OnStartup(object sender, StartupEventArgs e)
    {
        var vm = _ServiceProvider.GetRequiredService<ViewModels.Foo.TestViewModel>();
        var ws = ServiceContainer.Default.GetService<IWindowService>();
       ws.Show("TestView", vm);
    }

```

(Note code above doesn't work: `MissingMethodException: No parameterless constructor defined for type TestViewModel_0a31a372...`)



+ Some DX support info registers a viewmodel with GetPOCOType:

```
services.AddScoped(typeof(ViewModels.Foo.TestViewModel), ViewModelSource.GetPOCOType(typeof(ViewModels.Foo.TestViewModel)));
```
when is this recommended?

**Comment by AlexanderEgorov** [comment]
Yes, everything is correct.

As for the question of how to connect DX MVVM services to DI, when you call the IWindowService.Show method and pass a view name parameter, the service creates a View via the ViewLocator object. So, you can override the default ViewLocator by a custom one, which will use DI:

```C#
    public partial class App {
        public App() {
            ...
            _ServiceProvider = serviceCollection.BuildServiceProvider();
            ViewLocator.Default = new MyViewLocator(_ServiceProvider);
        }
    }
    class MyViewLocator : LocatorBase, IViewLocator {
        ServiceProvider _ServiceProvider;
        public MyViewLocator(ServiceProvider _ServiceProvider) {
            this._ServiceProvider = _ServiceProvider;
        }
        public object ResolveView(string name) {
            return _ServiceProvider.GetService(ResolveViewType(name));
        }
        public Type ResolveViewType(string name) { ... }
    }
```
See the attached [sample](https://github.com/DevExpress/DevExpress.Mvvm.Free/files/6156794/WpfApp1.zip).
