### ISSUE TITLE
ReSharper is reporting lots of "Cannot resolve property..." on POCO ViewModels

### ISSUE THREAD

**Issue by Tdue21** [DevExpress/DevExpress.Mvvm.Free#6]
I am having a lot of fun writing an application using this framework, and the POCO ViewModel approach makes everything a lot easier than normal when using MVVM. 

However, I get a lot of "Cannot resolve property 'XXXX' in data context of type 'XXXViewModel'" warnings from ReSharper as it is not able to connect stuff correctly as design time because of the way POCO ViewModels work. 

Is there anything that be done about this, or do I have to accept that this is the way it is?

Thank you for a great MVVM Framework.

**Comment by AlexanderEgorov** [comment]
Hi, 
 
Thank you for your feedback.
 
Yes, the same issue exists in the VS XAML designer and with XAML IntelliSense (it does not show command properties generated by the ViewModelSource). 
We already researched this issue before and were unable to overcome it on our side. So, I am afraid there is no way but to accept the current behavior or avoid using the POCO view models.

**Comment by Tdue21** [comment]
Yes, I figured as much. But I wanted to make sure you were aware of the "issue". 
Thank you for answering.

**Comment by malickf** [comment]
I just find it is possible to append the following code in the xaml and most of warning disappear ( virtual auto members are recognized, only command are still marked with warning ) : 

` d:DataContext="{d:DesignInstance viewModels:MainWindowViewModel}" `

note the `d:DesignInstance` part.

**Comment by malickf** [comment]
I just find it is possible to append the following code in the xaml and most of warning disappear ( virtual auto members are recognized, only command are still marked with warning ) :

`d:DataContext="{`d:DesignInstance` viewModels:MainWindowViewModel}"`

note the d:DesignInstance part.

As a full example : 

```
xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
mc:Ignorable="d"
...
mc:Ignorable="d"
DataContext="{dxmvvm:ViewModelSource Type=viewModels:MainWindowViewModel}"
d:DataContext="{d:DesignInstance viewModels:MainWindowViewModel}"  
```
