### ISSUE TITLE
Problem in Messenger

### ISSUE THREAD

**Issue by hossein-abdn** [DevExpress/DevExpress.Mvvm.Free#7]
Hi
I write simple code for using Messenger. but it doesn't work:
```
public partial class MainWindow : Window
{
	public MainWindow()
        {
            InitializeComponent();
            DevExpress.Mvvm.Messenger.Default.Register<string>(this, null, false, method1);
            DevExpress.Mvvm.Messenger.Default.Register<string>(this, null, false, method2);
        }
        void method1(string str)  { MessageBox.Show(str, "method1"); }
        void method2(string str)  { MessageBox.Show(str, "method2"); }
}
```
```
public class ViewModel
{
        public DevExpress.Mvvm.DelegateCommand TestCommand { get; set; }
        public ViewModel()
        {
            TestCommand = new DevExpress.Mvvm.DelegateCommand(ExecuteTestCommand);
        }
        private void ExecuteTestCommand()
        {
            DevExpress.Mvvm.Messenger.Default.Send("Test", typeof(string), null);
        }
}
```

I trace the code. The problem is In the DevExpress.Mvvm/Native/ActionInvoker/ActionInvokerBase.cs , Line 19:
```
if(messageTargetType == null || messageTargetType.IsAssignableFrom(target.GetType())) {
        Execute(parameter);
}
```
The type of messageTargetType is "string". but the type of targer is "MainWindow", so Execute Action never run.

**Comment by AlexanderEgorov** [comment]
Hi,
 
The **MessageTargetType** parameter in the **IMessenger.Send** function determines the object that should receive the message. In your case, it is the **MainWindow**. You can pass null to this parameter to send your message to all recipients.
BTW, you can add the **DevExpress.Mvvm** namespace and use one of the **IMessenger** extension methods provided by the static **MessengerExtensions** class.
